### ISSUE TITLE
I dont think I'm rotating properly after the first rotation??? 

### ISSUE THREAD

**Issue by dondondooooon** [dondondooooon/FYS3150#4]
The reason I ran this on a controlled for loop for 2 iterations is because I ran this originally under a while loop with the condition of max < eps && iterations < max_iterations... but then I got the same thing over and over again... i.e. only the first rotation or smthing of the sort.

<img width="1206" alt="Screen Shot 2021-09-27 at 09 39 01" src="https://user-images.githubusercontent.com/89593997/134865032-c0ee53ea-1cc5-4edb-89f4-a4901590b3ae.png">

**Comment by dondondooooon** [comment]
Here is the algorithm for the jacobi rotation I implemented...

<img width="566" alt="Screen Shot 2021-09-27 at 10 03 26" src="https://user-images.githubusercontent.com/89593997/134868464-f1266e82-3b96-4f66-9021-71a4d5c99dd6.png">

**Comment by dondondooooon** [comment]
Here is the max_offdiagonal function.. which I believe the problem isn't here tho.. but just in case:))

<img width="550" alt="Screen Shot 2021-09-27 at 10 04 36" src="https://user-images.githubusercontent.com/89593997/134868611-aa87c1a3-cba5-4edd-bac3-9f7252cef7b5.png">

**Comment by dondondooooon** [comment]
The reason I ran this on a controlled for loop for 2 iterations is because I ran this originally under a while loop with the condition of max < eps && iterations < max_iterations... but then I got the same thing over and over again... i.e. only the first rotation or smthing of the sort.

**Comment by anderkve** [comment]
Hi! I don't have much time to look at this, but two quick comments:

- You probably don't want to do `sqrt(A.size())` all the time. You know that A is a square matrix, so you can just check the numner of rows or columns, e.g. `int n = A.n_rows`
- I suspect the problem might be that you set `k=i+1` instead of `k=i`, and similarly for `l`.

If you need more help on this, please post it as an issue on the course GitHub repo, https://github.com/anderkve/FYS3150/issues Then all the teachers get notified and will answer if/when they have time. And you can also get help from other students who see your question -- and they can benefit from seeing the discussion on your post. 

Good luck!

**Comment by dondondooooon** [comment]
Jaaa! Takk det var feilen!!...

Jeg gjorde i+1 og j+1 for k og l opprinnelige fordi jeg printet dem ut på oppgave 4, og trengte å printe dem ut på matematisk indeks referrering. Det var ikke oppgave 4 handle om men jeg gjorde det bare for meg selv. Tusen takk anders!! 😃

**Comment by anderkve** [comment]
Så bra! Lykke til videre :)
